### ISSUE TITLE
Don't work. 1.86

### ISSUE THREAD

**Issue by wkornilow** [xfunforx/IngressXglyph#4]
Current version of Xglyph don't work in Ingress v1.86.

**Comment by hcarrega** [comment]
1.86.1 its live in store

**Comment by wkornilow** [comment]
Yep.  But when I wrote this issue, in store was 1.86 v

**Comment by xfunforx** [comment]
fixed it.

**Comment by xfunforx** [comment]
updated.

2015-11-04 23:06 GMT+08:00 wkornilow <notifications@github.com>:
